### ISSUE TITLE
Support for mac file system

### ISSUE THREAD

**Issue by dbjpanda** [ankitjain28may/drupal-best-practices#3]
Though I have not tested it yet. But probably your repo not going to work properly(slower performance) on mac due to slow mounting of volume.  [https://github.com/docker/for-mac/issues/77](url) . You may need to use docker-sync or other alternative. That's why I was suggesting to use an already existing one. Also separate everything as we discussed in IRC.

**Comment by dbjpanda** [comment]
Else mac user needs to use edge version with "cached" option. 
```
version: "2"

services:
  nginx-php:
    image: richarvey/nginx-php-fpm:latest
    container_name: nginx-php
    volumes:
#      - drupal-sync:/var/www/html:nocopy
       - ./drupal:/var/www/html:cached

    ports:
      - 80:80
#volumes:
#  drupal-sync:
#    external: true

  db:
    container_name: db
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: drupal
```
Remove comments from above to use with docker-sync
```
version: "2"

options:
  verbose: true
syncs:
  drupal-sync:
    src: './drupal'


```
